apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $.Values.appName }}-{{ $.Values.release }}-cm"
data:
  TCHALLENGE_MONGODB_DATABASE: tchallenge
  TCHALLENGE_MONGODB_PORT: "27017"
  TCHALLENGE_MONGODB_HOST: tchallenge-db-route-1-projecton2206.openshift.devops.t-systems.ru
  TCHALLENGE_MONGODB_USERNAME: root
  TCHALLENGE_MONGODB_PASSWORD: Admin123!
  TCHALLENGE_MONGODB_AUTHDB: admin
