apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ $.Values.appName }}-{{ $.Values.release }}-route"
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: "{{ $.Values.service.outerPort }}-tcp"
  to:
    kind: Service
    name: "{{ $.Values.appName }}-{{ $.Values.release }}-service"
