apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Values.appName }}-{{ $.Values.release }}-service"
  labels:
    deploymentUnit: "{{ $.Values.appName }}-db"
    release: {{ .Values.release }}
spec:
  selector:
      deploymentUnit: "{{ $.Values.appName }}-db"
      release: {{ .Values.release }}
  ports:
    - name: 27017-tcp
      port: 27017
      targetPort: 27017
  type: ClusterIP
