apiVersion: v1 // used by kubernetes, see docs
kind: Pod
metadata:
  name: manual-bash // название пода
spec:
  containers:  //контейнер который будет в поде
    - name: bash // имя контейнера
      image: ubuntu:16.04
      command: bash // зайти в контейнер и выполнить эту команду с аргументами.
      args: [-c "while true; do sleep 1; date; done"]
