apiVersion: v1
kind: Pod
metadata:
	name: manual-backend
	labels:
		tier: backend
spec:
	containers:
  	- name: web // имя контейнера
  		image: myimageregistry.local/backend:15.0.4 // имадж, который выкачается из реджистри и будет в поде (имя и адрес)
  		command: /usr/bin/start // обычная команда, выполн. в контейнере
// куб сам скачивает имадж и разворачивает его.
// поды не пересоздаются автоматически! только в реплике.