apiVersion:  extensions/v1beta1
kind: Ingress
metadata:
  name: sturm-app-ingress
  labels:
    deploymentUnit: sturm-app-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /sturmapp
            backend:
              serviceName: sturm-app-service
              servicePort: 80
