apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"app-katze","artifactId":"app-katze-openshift","buildTime":"20200707.120237","deploymentUnit":"app-katze-openshift","generatedBy":"openshift-maven-plugin","groupId":"","version":"1.14.70.35-SNAPSHOT"},"name":"app-katze","namespace":"oc-project-1"},"spec":{"ports":[{"name":"9080-tcp","port":9080,"protocol":"TCP","targetPort":9080},{"name":"8080-tcp","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"deploymentconfig":"app-katze"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: '2020-07-07T09:29:58Z'
  labels:
    app: app-katze
    artifactId: app-katze-openshift
    buildTime: '20200707.120237'
    deploymentUnit: app-katze-openshift
    generatedBy: openshift-maven-plugin
    groupId: ''
    version: 1.14.70.35-SNAPSHOT
  name: app-katze
  namespace: oc-project-1
  resourceVersion: '14454349'
  selfLink: /api/v1/namespaces/oc-project-1/services/app-katze
  uid: 6cd853bc-c034-11ea-ac98-c2a16f3dd721
spec:
  clusterIP: 172.30.153.156
  ports:
    - name: 9080-tcp
      port: 9080
      protocol: TCP
      targetPort: 9080
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentconfig: app-katze
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
